DROP DATABASE IF EXISTS CT;

CREATE DATABASE CT;

USE CT;

CREATE TABLE ETH (
id int not null auto_increment,
price DECIMAL(7, 2),
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

CREATE TABLE BTC  (
id int not null auto_increment,
price DECIMAL(7, 2),
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

CREATE TABLE DOGE (
id int not null auto_increment,
price DECIMAL(7, 2),
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);